### ISSUE TITLE
Unable to use astroARIADNE

### ISSUE THREAD

**Issue by SwastikC** [jvines/astroARIADNE#18]
Hi. I am trying to use the astroARIADNE but I am unable to do so . I am getting an error in the first step itself. can you please help me. I am attaching the screenshot of it.
![sss](https://user-images.githubusercontent.com/68861854/105721587-be4f0380-5f4a-11eb-8acd-f9c7ee6656fb.png)

**Comment by SwastikC** [comment]
Hi. I have sorted this issue. It is due to progressbar and progressbar2.. After removing progressbar it worked

**Comment by jvines** [comment]
Hi, sorry I missed this. I didn't get an email with the notification.

It seems the problem is with dustmaps and not ARIADNE. Did you install dustmaps correctly?

**Comment by SwastikC** [comment]
yes. It is working fiine
