### ISSUE TITLE
Issue in star module

### ISSUE THREAD

**Issue by deepjyotisatpathy18032** [jvines/astroARIADNE#22]
As you can see the error, I tried resolving it by going to that particular directory. I found "data" folder but inside that it had folder named "bh" and inside that it had "bh.h5" file. The file code is searching for is not there. Do I need to download this fits file named "SFD_dust_4096_ngp.fits" separately from somewhere because I guess dustmaps is installed properly.
![Screenshot 2021-07-24 at 12 52 56 AM](https://user-images.githubusercontent.com/61833438/126831786-90d1321a-d902-42ed-8ebe-dd7fc35a3e91.png)

**Comment by kevinkhu** [comment]
You need to import the SFD dustmap first. This will download the dustmap and save it to your dustmaps directory:
`import dustmaps.sfd`
`dustmaps.sfd.fetch()`

**Comment by jvines** [comment]
As @kevinkhu said, the dustmaps must be fetched prior to being used with ARIADNE.
