### ISSUE TITLE
Pointer being freed was not allocated

### ISSUE THREAD

**Issue by AstroSong** [jvines/astroARIADNE#24]
Hi @jvines  I have a problem when I import the astroARISDNE package. I use python3.7.8 in Mac. The error messages are as follows,

>>> from astroARIADNE.star import Star
Python(40154,0x10181edc0) malloc: *** error for object 0x7fff8ee56950: pointer being freed was not allocated
Python(40154,0x10181edc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

I tried to figure it out but failed. Thanks for your  help.
Song

**Comment by jvines** [comment]
Hi,

I think I have encountered this before. I think it occurred to me due to a failed installation. Did you try uninstalling the package and installing it again?

**Comment by AstroSong** [comment]
I re-install the astroARIADNE but still get the problem : (

**Comment by jvines** [comment]
Try creating a fresh environment. It could be a dependency that's failing. A way to test this is to import the dependencies by themselves (numpy, numba, matplotlib, etc etc) and seeing if that same error pops up again!

**Comment by AstroSong** [comment]
I checked the problem report carefully, and found one sentence:
Application Specific Information:

> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/healpy/_healpy_pixel_lib.cpython-37m-darwin.so
> abort() called
> Python(29291,0x10fef1dc0) malloc: *** error for object 0x7fff8e58f950: pointer being freed was not allocated

So I uninstall healpy and astroARIADNE, and re-install them. Now it's ok. You are right that it was caused by some other packages. Thanks!

**Comment by jvines** [comment]
Great to hear that! I'll close this issue then :)
