### ISSUE TITLE
an error for import

### ISSUE THREAD

**Issue by AstroJLin** [jvines/astroARIADNE#31]
Hi Jvines:

When I try to run ''from astroARIADNE.star import Star'', an error is reported.  Can you tell me why?

Thanks!
The error is as follow:

File "/home/jlin/anaconda3/lib/python3.8/site-packages/astropy/units/_typing.py", line 9, in <module>
  from typing import Annotated

builtins.ImportError: cannot import name 'Annotated' from 'typing' (/home/jlin/anaconda3/lib/python3.8/typing.py)

During handling of the above exception, another exception occurred:

￼ File "/home/jlin/ARIADNE/astroARIADNE-master/untitled-1.py", line 1, in <module>
  from astroARIADNE.star import Star
￼ File "/home/jlin/ARIADNE/astroARIADNE-master/astroARIADNE/__init__.py", line 12, in <module>
  from .fitter import Fitter
￼ File "/home/jlin/ARIADNE/astroARIADNE-master/astroARIADNE/fitter.py", line 10, in <module>
  import astropy.units as u
File "/home/jlin/anaconda3/lib/python3.8/site-packages/astropy/units/__init__.py", line 39, in <module>
  from .decorators import *
File "/home/jlin/anaconda3/lib/python3.8/site-packages/astropy/units/decorators.py", line 13, in <module>
  from . import _typing as T
File "/home/jlin/anaconda3/lib/python3.8/site-packages/astropy/units/_typing.py", line 18, in <module>
  from typing_extensions import * # override typing

builtins.AttributeError: module 'typing_extensions' has no attribute 'OrderedDictTypedDict'

**Comment by jvines** [comment]
Hi.

It seems this error is related to your astropy or typing_extensions installations. Please try reinstalling both modules.

Jose V.

**Comment by AstroJLin** [comment]
Hi Jose V,

I have reinstalled both modules. However, the error still exists.  

Thanks!

**Comment by jvines** [comment]
If you do `import astropy.units as u`  in a separate terminal, does the error appear?

**Comment by AstroJLin** [comment]
Yes! when I import astropy.units as u in a separate terminal,  the error is reported.

In addition, I can not install astroARIADNE using the pip, when I use  pip install astroARIADNE, the error as follow:
![Screenshot from 2022-06-20 00-11-56](https://user-images.githubusercontent.com/86318178/174490275-06cc3990-68f0-44bb-8a26-c0853b68a123.png)

**Comment by jvines** [comment]
In that case the error is not with ARIADNE but with astropy instead.

Also ARIADNE is not installable through pip yet :( I’m working on a final update before pushing to the PyPi servers.

Since the error is external I’ll close this issue now, but feel free to re-open it or create a new one if something else pops up.

Cheers,

Jose V.
