### ISSUE TITLE
How to add W3 and W4 filters  in ARIADNE

### ISSUE THREAD

**Issue by AstroJLin** [jvines/astroARIADNE#32]
Hi,

Here, I shoud how to add WISE_RSR_W3,WISE_RSR_W4 and APASS filters in ARIADNE.  These filters don't seem to be included in a list of allowed filters for the ARIADNE.

Thanks!

**Comment by jvines** [comment]
I mean that Phoenix V2 models do not cover W3 and W4. I need to check if Kurucz and C&K do, but I think they don't, which is why I didn't include them. In addition, these could be prone to infrared excess which could bias results anyway.

[The APASS catalog](https://vizier.u-strasbg.fr/viz-bin/VizieR?-source=II/336) has V B g' r' i' magnitudes, which are in ARIADNE

**Comment by jvines** [comment]
Yes, checking with my model creation tool it seems it does extend and it's just Phoenix V2 the one that doesn't.

In any case, the fact remains that I want consistency between all models, so given Phoenix V2 doesn't reach W3 and W4 I won't make them available for fitting.

I am working in an update that includes both W3 and W4 for visualization purposes only, however.

**Comment by AstroJLin** [comment]
Hi,
Thank you very much for your reply.

If I want to include both W3 and W4 into the fit of the ARIADNE, can I try to fix the code in my machine?

Can you provide some suggestions for adding both W3 and W4 in the ARIADNE.

**Comment by jvines** [comment]
You can do whatever you want with the code in your machine, however, I won't be able to provide support.

I am adding W3 and W4 to the model grid so you'll need to either wait until that's ready or compile the models yourself, which means convolving the model spectra with the filter response functions and then integrating that flux.

Creating the model grid is an intensive task so it'll take me a couple of days to have it ready.

**Comment by jvines** [comment]
I mean that I will add them to the model grid but you won't be able to fit with them.

If you want to use them to fit with them you would need to enable it within the code. Convolving the model spectra and integrating is only necessary to create the model grid.

I don't understand your second question

**Comment by AstroJLin** [comment]
Hi,
 
Here, my second question is that the obtained stellar parameters in your paper don't seem to include the fit for W3 and W4, which results from lack of the W3 and W4 observation or you didn't join the fit ? 
 
Thanks

**Comment by jvines** [comment]
Oh.. well, of course it doesn't include W3 and W4. The paper explicitly states we only used W1 and W2.

**Comment by AstroJLin** [comment]
Hi, 

Many thanks.

Actually, I have a question why don't you consider adding W3 and W4 data if the source have W3 and W4 observation.
Is this due to W3 and W4 may be contaminated with radiation from dust?

**Comment by jvines** [comment]
I already told you why in my first answer.

To reiterate: I wanted photometric consistency between all models. If one filter was outside of the wavelength range of a given model, then I wouldn't use it in any model.

There was no reason to add the data if it wasn't used.

**Comment by AstroJLin** [comment]
Thank you so much for your patience.

**Comment by jvines** [comment]
Happy to help.

I'll close this now, but if anything pops up feel free to reopen.
