### ISSUE TITLE
error when plot SED (nonposx and nonposy)

### ISSUE THREAD

**Issue by zzxihep** [jvines/astroARIADNE#35]
When I plot the SED of the fitting result, there is a error like this:

code:
```python
ax.set_xscale('log', nonposx='clip')
```

```shell
TypeError: LogScale.__init__() got an unexpected keyword argument 'nonposx'
```
It seems that the arguments 'nonposx' and 'nonposy'  are no longer supported in Matplotlib.

**Comment by jvines** [comment]
Fixed in version 1.0.4 by changing nonposx/y to nonpositive.

Thanks for catching this.
