### ISSUE TITLE
plotter.py error

### ISSUE THREAD

**Issue by denizcdursun** [jvines/astroARIADNE#37]
Hello @jvines,
I am getting error in plotter.py file. When the "btsetll" model is most compatible, I get this error:

`Plotting SED
Traceback (most recent call last):
  File "HD345957.py", line 86, in <module>
    artist.plot_SED()  # Plots stellar SED with model included
  File "/Users/Deniz/Downloads/astroARIADNE-master-2/astroARIADNE/plotter.py", line 412, in plot_SED
    self.SED(ax)
  File "/Users/Deniz/Downloads/astroARIADNE-master-2/astroARIADNE/plotter.py", line 604, in SED
    new_w = np.linspace(wave[0], wave[-1], len(wave))
IndexError: index 0 is out of bounds for axis 0 with size 0`

**Comment by jvines** [comment]
Hi,

Can you tell me what the best fitting teff, log g, and Fe/H are?

**Comment by jvines** [comment]
Do you have the file `lte056-4.0-1.0Za+0.0.BT-Settl.AGSS2009.fits` in your models folder?

**Comment by denizcdursun** [comment]
Oh, I don't have. I downloaded all the files from the link you wrote. 

I have before `lte006-3.0-0.0a+0.0.BT-Settl.CIFIST2011.fits` and after `lte006-3.0-0.0.BT-Settl.AGSS2009.fits` 

Is there a code where I can pull all files at once?

**Comment by jvines** [comment]
There's a link in the README for the BT- family of models. There you can find a file with wget instructions for all models.

If you need further clarification please let me know.
