### ISSUE TITLE
ValueError: Specify the name of the RA/Dec columns in the input table.

### ISSUE THREAD

**Issue by BreezeAndNeco** [jvines/astroARIADNE#41]
When I run the code, I got a problem follow:
`ra = 332.61557795031325
dec = 16.708073232841233
starname = 'Kn5_Standard'
gaia_id = 1775289689164181888

s = Star(starname, ra, dec, g_id=gaia_id)

		#####################################
		##             ARIADNE             ##
		#####################################
   spectrAl eneRgy dIstribution bAyesian moDel averagiNg fittEr

			Author : Jose Vines
			Contact : jose . vines at ug . uchile . cl
			Star : Kn5_Standard
		*** LOOKING UP ARCHIVAL INFORMATION ***
INFO: Query finished. [astroquery.utils.tap.core]
Warning!: CatalogWarning
Warning message: Parameter radius not found! Be advised.
Warning!: CatalogWarning
Warning message: Parameter lum not found! Be advised.
INFO: Query finished. [astroquery.utils.tap.core]
INFO: Query finished. [astroquery.utils.tap.core]
Star not found in catalog Pan-STARRS.
INFO: Query finished. [astroquery.utils.tap.core]
INFO: Query finished. [astroquery.utils.tap.core]
INFO: Query finished. [astroquery.utils.tap.core]
INFO: Query finished. [astroquery.utils.tap.core]
Looking online for archival magnitudes for star Kn5_Standard
Checking catalog APASS
Warning!: CatalogWarning
Warning message: Vmag magnitude error is 0, assigning error.
Warning!: CatalogWarning
Warning message: Bmag magnitude error is 0, assigning error.
Warning!: CatalogWarning
Warning message: g_mag magnitude error is 0, assigning error.
Warning!: CatalogWarning
Warning message: r_mag magnitude error is 0, assigning error.
Warning!: CatalogWarning
Warning message: i_mag magnitude error is 0, assigning error.
Checking catalog All-WISE
Checking catalog Gaia DR3
Checking catalog 2MASS
Checking catalog GLIMPSE
Warning!: CatalogWarning
Warning message: Star is not available in catalog GLIMPSE. Skipping
Checking catalog SDSS DR12
Warning!: CatalogWarning
Warning message: Catalog SDSS entry is either an extended source, is of bad quality or is contaminated. Skipping.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/lk/5vm5tt_56jxggx405m4yj79h0000gn/T/ipykernel_4657/2163093052.py in <cell line: 6>()
      4 gaia_id = 1775289689164181888
      5 
----> 6 s = Star(starname, ra, dec, g_id=gaia_id)

~/opt/anaconda3/lib/python3.9/site-packages/astroARIADNE/star.py in __init__(self, starname, ra, dec, g_id, plx, plx_e, rad, rad_e, temp, temp_e, lum, lum_e, dist, dist_e, Av, Av_e, offline, mag_dict, verbose, ignore, dustmap)
    184                                 c)
    185                     )
--> 186                 lib = Librarian(starname, self.ra, self.dec, g_id=self.g_id,
    187                                 mags=self.get_mags, ignore=ignore)
    188                 self.g_id = lib.g_id

~/opt/anaconda3/lib/python3.9/site-packages/astroARIADNE/librarian.py in __init__(self, starname, ra, dec, radius, g_id, mags, ignore)
    165         if mags:
    166             self.gaia_query()
--> 167             self.get_magnitudes()
    168             idx = self.used_filters >= 1
    169             self.used_filters[idx] = 1

~/opt/anaconda3/lib/python3.9/site-packages/astroARIADNE/librarian.py in get_magnitudes(self)
    346                 continue
    347             elif c == 'GALEX':
--> 348                 current_cat = self._gaia_galex_xmatch(cats, self.ra, self.dec,
    349                                                       self.radius)
    350                 if len(current_cat) == 0:

~/opt/anaconda3/lib/python3.9/site-packages/astroARIADNE/librarian.py in _gaia_galex_xmatch(cats, ra, dec, radius)
    792                          dec=dec * u.deg, frame='icrs')
    793         region = CircleSkyRegion(coord, radius=radius)
--> 794         xm = XMatch.query(cat1='vizier:I/345/gaia2', cat2=galex,
    795                           colRA2='RAJ2000', colDec2='DEJ2000',
    796                           area=region, max_distance=radius)

~/opt/anaconda3/lib/python3.9/site-packages/astroquery/xmatch/core.py in query(self, cat1, cat2, max_distance, colRA1, colDec1, colRA2, colDec2, area, cache, get_query_payload, **kwargs)
     69             Query results table
     70         """
---> 71         response = self.query_async(cat1, cat2, max_distance, colRA1, colDec1,
     72                                     colRA2, colDec2, area=area, cache=cache,
     73                                     get_query_payload=get_query_payload,

~/opt/anaconda3/lib/python3.9/site-packages/astroquery/xmatch/core.py in query_async(self, cat1, cat2, max_distance, colRA1, colDec1, colRA2, colDec2, area, cache, get_query_payload, **kwargs)
     98         kwargs = {}
     99 
--> 100         self._prepare_sending_table(1, payload, kwargs, cat1, colRA1, colDec1)
    101         self._prepare_sending_table(2, payload, kwargs, cat2, colRA2, colDec2)
    102         self._prepare_area(payload, area)

~/opt/anaconda3/lib/python3.9/site-packages/astroquery/xmatch/core.py in _prepare_sending_table(self, cat_index, payload, kwargs, cat, colRA, colDec)
    132         if not self.is_table_available(cat):
    133             if ((colRA is None) or (colDec is None)):
--> 134                 raise ValueError('Specify the name of the RA/Dec columns in' +
    135                                  ' the input table.')
    136             # if `cat1` is not a VizieR table,

ValueError: Specify the name of the RA/Dec columns in the input table.
`

How can I solve this problem?

**Comment by jvines** [comment]
Hi!

Is this still a problem for you??

Cheers

**Comment by jvines** [comment]
I'll close this. If it pops again please do let me know
