### ISSUE TITLE
Error while running just one model 

### ISSUE THREAD

**Issue by cosmicbabs** [jvines/astroARIADNE#42]
Hi! 

While fitting just one model (Phoenix), I get an error since there the keyword max_prob_mod is set to 'btsettl'
<img width="1093" alt="Screen Shot 2022-10-25 at 13 59 44" src="https://user-images.githubusercontent.com/16668370/197839913-5b90966b-8fbf-4854-b5ee-3d1ef3caaeca.png">
<img width="1086" alt="Screen Shot 2022-10-25 at 13 59 57" src="https://user-images.githubusercontent.com/16668370/197839955-9aa27f5a-153b-4eb0-8bd4-8e9c2d93e0d1.png">

I'm not sure why the code assumes that btsettl should be the model if I'm just running Phoenix ... could it be a bug? 

Best,
Bárbara

**Comment by jvines** [comment]
This should be fixed now!
