### ISSUE TITLE
How to get the SED data?

### ISSUE THREAD

**Issue by BreezeAndNeco** [jvines/astroARIADNE#46]
I managed to fit and plot the diagram, but I did not find the SED data which support to plot in the file MBA.pkl. Could you help me?

**Comment by jvines** [comment]
Hi @BreezeAndNeco ,

Which data are you looking for? The synthetic fluxes are stored in another file, for example.

**Comment by BreezeAndNeco** [comment]
Hi Jose Vines,

I want to know the flux data used to plot SED diagram, which is the balck line in SED diagram.

Thanks.



At 2023-02-20 02:15:33, "Jose Vines" ***@***.***> wrote:

Hi @BreezeAndNeco ,

Which data are you looking for? The synthetic fluxes are stored in another file, for example.

**Comment by jvines** [comment]
The black line is not stored in BMA.pkl

Please refer to [this section](https://github.com/jvines/astroARIADNE#in-order-to-plot-the-models-you-have-to-download-them-first) of the documentation to see where you can find those models, though be advised that the BT-XXX models are out of date in that section.

**Comment by jvines** [comment]
I'll close this now. If anything else pops up, please let me know
