### ISSUE TITLE
BT models 

### ISSUE THREAD

**Issue by beginner111111** [jvines/astroARIADNE#49]
When I tried to download BT models from http://osubdd.ens-lyon.fr/phoenix/, only fits files (17kB per file) are available, which only contain the header information but does not contain wave and fluxes of synthetic spectra. How can I download the synthetic spectra of BT models ?

download way: e.g.,
wget "http://osubdd.ens-lyon.fr/phoenix/phoenix.cgi?c=i&a=mime:application/fits&o=phoenix:Grids/BT-Cond/SPECTRA/lte008-4.0-0.0a+0.0.BT-Cond.7.bz2" -O "lte008-4.0-0.0a+0.0.BT-Cond.CIFIST2011.fits"

**Comment by jvines** [comment]
Try downloading them from VOSA. They might need resampling to make the wavelength step constant, however.
