### ISSUE TITLE
Error plotting results: Problem with FITS files

### ISSUE THREAD

**Issue by cezeva** [jvines/astroARIADNE#51]
Hello,

I have encountered an error when attempting to visualize the results. The specific error message is as follows:

OSError: No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True

![Captura desde 2023-11-03 16-57-01](https://github.com/jvines/astroARIADNE/assets/149844249/ee22ff79-3e5a-4bd2-bd7d-fbd4636db1c7).

I believe the issue may be related to the file format of my models, as they are currently in ASCII format. One potential solution could involve converting all of my model files from ASCII to .fits format. However, this process may be cumbersome due to the large number of files involved.

Do you have any alternative solutions or suggestions for addressing this issue?

Thank you for your assistance in resolving this issue.

Best regards

**Comment by jvines** [comment]
The problem appears to be the BT-Settl models, which fits files that disappeared from the phoenix website for whatever reason. I know there is a source for them somewhere, but I haven't made the time or effort to look for them, as they're just used for plotting so they're easily substituted. I would recommend you plot using another type of model, such as the Kurucz ones.

**Comment by jvines** [comment]
The source I mentioned could be VOSA.
