### ISSUE TITLE
grav_mass is very different from iso_mass

### ISSUE THREAD

**Issue by hewlang** [jvines/astroARIADNE#69]
Hello,

I fitted some stars and compared their grav_mass and iso_mass, finding that grav_mass is very different from iso_mass, as shown in the figure below.

I reviewed the code and found that grav_mass is used as a prior to estimate iso_mass. In addition, corner plots and SED plots behave well. I would like to ask, what could be the possible reasons for grav_mass being very different from iso_mass?

<img width="545" alt="grav_mass vs  iso_mass" src="https://github.com/user-attachments/assets/8055f4ce-4a0d-49b9-b4b9-80e3e603cf93">

**Comment by jvines** [comment]
You can find a discussion about that in the paper.

_______________________________________
Dr. José Vines.
Postdoctoral Researcher
Astrophysics Institute
Universidad Católica del Norte

www.jvines.cl

**Comment by hewlang** [comment]
> You can find a discussion about that in the paper.
> […](#)

Thank you for answer!
